keycloak:
  auth-server-url: http://localhost:8484/auth
  realm: Lavka
  resource: client
  public-client: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect : org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui





#keycloak.realm=SpringBootKeycloak
#keycloak.resource=login-app
#keycloak.public-client=true
